#!/bin/bash
set -ue
FILE=${1-}
M2DIR=~/M2-Planet/M2-Planet
LIBDIR="${M2DIR}/M2libc"
incl=$(cpp -D_STDC_PREDEF_H -D__M2__ -D__i386__ -nostdinc -I "$LIBDIR" "$FILE"  -M |\
tr '\n' 'X' | sed 's/^[^ ]* [^ ]* \\X //;s/ \\X /\n/g;s/X$//'
)

cpp -D__M2__ -D__i386__ -nostdinc -I "$LIBDIR" "$FILE" -H -P -o out.i
ARCH=x86

# not in exact resolution order
: <<'COMMENT'
cat > out.kaem  <<EOF
set -ue

rm -f out.M1 out.hex2 out

${M2DIR}/bin/M2-Planet \\
	--architecture ${ARCH} \\
EOF
echo "$incl" | sed 's/^/\t-f /;s/$/ \\/' >> out.kaem
cat >> out.kaem  <<EOF
	-f ${FILE} \\
	-o out.M1

M1 -f ${LIBDIR}/${ARCH}/${ARCH}_defs.M1 -f ${LIBDIR}/${ARCH}/libc-core.M1 -f out.M1 --little-endian --architecture ${ARCH} -o out.hex2
hex2 -f ${LIBDIR}/${ARCH}/ELF-${ARCH}.hex2 -f out.hex2 --little-endian --architecture ${ARCH} --base-address 0x8048000 -o out

EOF

#kaem --verbose -f out.kaem
#bash -v out.kaem
COMMENT

${M2DIR}/bin/M2-Planet \
	--architecture ${ARCH} \
	-f out.i \
	-o out.M1

M1 -f ${LIBDIR}/${ARCH}/${ARCH}_defs.M1 -f ${LIBDIR}/${ARCH}/libc-core.M1 -f out.M1 --little-endian --architecture ${ARCH} -o out.hex2
hex2 -f ${LIBDIR}/${ARCH}/ELF-${ARCH}.hex2 -f out.hex2 --little-endian --architecture ${ARCH} --base-address 0x8048000 -o out
