#define FILL 0
/*
#undef  ELFCLASS32
#define ELFCLASS32 FILL
#undef  ELFDATA2LSB
#define ELFDATA2LSB FILL
#undef  EV_CURRENT
#define EV_CURRENT FILL
*/
#undef  ELFOSABI_SYSV
#define ELFOSABI_SYSV FILL
#undef  ELFOSABI_SYSV
#define ELFOSABI_SYSV FILL
#undef  ELFOSABI_SYSV
#define ELFOSABI_SYSV FILL
#undef  ELFOSABI_SYSV
#define ELFOSABI_SYSV FILL

